
import React, { useState } from 'react';
import { Transition } from '@headlessui/react';
import { List, ListItem } from '@material-tailwind/react';

const Privacypage = () => {
  const sections = [
    {  id:1, title: "GENERAL", description: "Description for Dashboard" },
    { id:2,
      title: "COLLECTION OF PERSONAL AND OTHER INFORMATION",
      description:
        "Description for Collection of Personal and Other Information",
    },
    { id:3,title: "COOKIES", description: "Description for Cookies" },
    { id:4,
      title: "DIVULGING/SHARING OF PERSONAL INFORMATION",
      description: "Description for Divulging/Sharing of Personal Information",
    },
    { id:5,
      title: "SECURITY",
      description: "Description for Divulging/Sharing of Personal Information",
    },
    { id:6,
      title: "THIRD PARTY ADVERTISEMENTS / PROMOTIONS",
      description: "Description for Divulging/Sharing of Personal Information",
    },
    { id:7,
      title: "USER’S CONSENT",
      description: "Description for Divulging/Sharing of Personal Information",
    },
    {id:8,
      title: "CHILDREN INFORMATION",
      description: "Description for Divulging/Sharing of Personal Information",
    },
    {
        id:9,
      title: "GRIEVANCE OFFICER",
      description: "Description for Divulging/Sharing of Personal Information",
    },
    {
        id:10,
      title: "DISPUTE RESOLUTION AND JURISDICTION",
      description: "a) This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.b) This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of fittingswale.comc) The domain name www.fittingswale.com(`Website`), is owned and operated by Mittal enterprises, and having its office at Mittal bhawan Manaitand near Golbuilding Dhanbad Jharkhand- 826001, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.f) The use of the Website by the User is solely governed by this Policy as well as the Terms of Use of the Website (“Terms”, available at www.fittingswale.com), and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. Visiting the home page of the Website and/or using any of the services provided on the Website shall be deemed to signify the User’s unequivocal acceptance of this Policy and the aforementioned Terms, and the User expressly agrees to be bound by the same. The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry / termination of either one will lead to the termination of the other.",
    },
  ];

  const [selectedSection, setSelectedSection] = useState(null);

  const handleSectionClick = (sectionId) => {
    setSelectedSection(sectionId);
  };

  return (
    <div className="flex flex-col mt-40 md:flex-row h-screen">
      <div className="w-full md:w-1/4 bg-gray-200 p-4">
        <h2 className="text-lg font-bold mb-4">Privacy Policy</h2>       
        <List>
          {sections.map(section => (
            <ListItem key={section.id} onClick={() => handleSectionClick(section.id)} className="cursor-pointer hover:text-blue-500 mb-2">
              {section.title}
            </ListItem>
          ))}
       </List>
      </div>
      <Transition
        show={selectedSection !== null}
        enter="transition ease-out duration-300 transform"
        enterFrom="translate-x-full"
        enterTo="translate-x-0"
        leave="transition ease-in duration-200 transform"
        leaveFrom="translate-x-0"
        leaveTo="translate-x-full"
        className="w-full md:w-3/4 bg-white p-4 overflow-y-auto"
      >
        {(ref) => (
          <div ref={ref}>
            {selectedSection !== null && (
              <div>
                <h2 className="text-lg font-bold mb-4">{sections[selectedSection - 1].title}</h2>
                <p>{sections[selectedSection - 1].description}</p>
              </div>             
            )}
          </div>         
        )}
      </Transition>
      <hr></hr>
    </div>
  );
};

export default Privacypage;
